apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWVNqb21BSHBFNXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1UY3dOelUwTVRkYUZ3MHpOakEyTVRRd056VTVNVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR4SjJpN3VRNlRMRUtpZ0h6bXFoUGt4c2dHTFpUZEVxK0x0WW9WT3M3amhrZFdqUEhBdTQ2cjBvYnIKcFR0elQ0NWlBL1JCSWlLcXZOQjk3VnhwMkVIbWJYZjJGMlV1RGNxU3VsSVZwYnNpSjZTZlZUa2FGSStzVkhzQwo3UitPZFhwYlRSQVFyZEJKeUxEWFNTYjgzV2RsOGdaRHFOOEVWcTBEeEh2S04xYm9ZWlEvM1Y5U0pNd0M4bFZxCmU4L01tVGlvYWRybE11VExpL1RlNENnanloSWlQN3JDaE9DWG9GWElmN3pFM0licG56V25PVkpYazI0aVFTaEkKRDlVL0ZnVVBCbmdNcmFuOGVyY2RGUEFtUWEwT0VtREZuaXNoY2ZIZEk5cHNxQThVeVJnWnE1RFc3M0FHQlR2TQpFUWlDdytDTkg1UWN1WE1vQXJxMkx3MnQ4azZUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTbzNYczQwR1RhbkpPZ3V2SlJDSHNucldRU1JUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWZvc3dFaHdrVgpncHFkbW1mTzIyL2lhZElTaUJiT2RTZzltWCtJN2puVUt3QnlHWkt1RmFRaDdYeHNPbmhBcXBnU1pnalpLYUJnCndFdkxwWThORXBQVWxQVWwxUWNmcVBZVHVHbXZ6d0tncmVPZ0F3bkoyaGRmYW8wZzRzdUFLb2lYWUxPbTJsSDkKRlJsK3p3MUVYK1lmRE8rZEJyYTc0NDZaWDhUOG5jSXJqYjBrSW5WRUFudU84cXZOaXpHWkorQm5SUGMvYXBnVApRdFQ1UEhTaVhMdjVCWUN5MjIwRVNFWTVDZnRrYzRpelp3dnJaUmFtRXhNQnAzeTlPQmlvN3BqSnlUNDNpQkt5CmJZVEZZNm5zMXcvV2Vqb0FxK1Q2V3dZSnJyc2x3YmJBV0U5NGVNbDY4MXFVWnl6ZkdXQUp5Q1dqbXFlUlZRWDcKbk5UNno3aFcyd3QwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

    server: https://192.168.1.91:6443
  name: kubernetes

users:
- name: max
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZCMHNEWXhTZDQzWXNFeXhsVi1CcTB0WVZ5QVhZQk91d182NW5sRU1fSTQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzgxNzg3NDA5LCJpYXQiOjE3ODE3ODM4MDksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMmFkNDlmMzUtOWQwMi00MmIxLWFlZjctZDU4MTdmYWQ2YWQ1Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJyYmFjIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im1heCIsInVpZCI6ImZjNzJhOTNhLWU4ZTktNDUyNS04YjNlLWNiNTAxYWZmZDc5MCJ9fSwibmJmIjoxNzgxNzgzODA5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6cmJhYzptYXgifQ.jUCW7XB9PYAhxTIqpzp-SR-3s5hRRe5dhZ8TgYWQldygN7PsgEzqYnvN_V6_9VRrwRv-PnpaByrFXxbgY5iWIrKDuLDKFMfoDUYKK0xeigAkxjCrcXZ3EJwp66B6uatfHNpPNHkRMZauh7YU1SHy4kZU3TEH_3uV2pjr-6F3K6MODeigKpvmDejyTJY6iF5PSLJwxvIu78PFHlRBPL18jZmSNVAhTiT8Tom9Z4aI0ZNp6RvXnQmQc0PG1CauRvqF2usKwomBQPMygn12P2kopsENrHOwPC_pntTG0wWJkMoA2eMZOW-9_P6mj2fbg7gjuGokYNW3qY9iHIlEC7EQ5Q

contexts:
- context:
    cluster: kubernetes
    user: max
    namespace: jenkins
  name: max-context

current-context: max-context


# kubectl config view --raw (to get  certificate-authority-data and add in that section) 
# kubectl create token max -n rbac (ADD THIS TOKEN IN SUNJAY-CONFIG.YAML)
# kubectl --kubeconfig=max-config.yaml get pods
# kubectl create token max -n rbac