apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWVNqb21BSHBFNXd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1UY3dOelUwTVRkYUZ3MHpOakEyTVRRd056VTVNVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR4SjJpN3VRNlRMRUtpZ0h6bXFoUGt4c2dHTFpUZEVxK0x0WW9WT3M3amhrZFdqUEhBdTQ2cjBvYnIKcFR0elQ0NWlBL1JCSWlLcXZOQjk3VnhwMkVIbWJYZjJGMlV1RGNxU3VsSVZwYnNpSjZTZlZUa2FGSStzVkhzQwo3UitPZFhwYlRSQVFyZEJKeUxEWFNTYjgzV2RsOGdaRHFOOEVWcTBEeEh2S04xYm9ZWlEvM1Y5U0pNd0M4bFZxCmU4L01tVGlvYWRybE11VExpL1RlNENnanloSWlQN3JDaE9DWG9GWElmN3pFM0licG56V25PVkpYazI0aVFTaEkKRDlVL0ZnVVBCbmdNcmFuOGVyY2RGUEFtUWEwT0VtREZuaXNoY2ZIZEk5cHNxQThVeVJnWnE1RFc3M0FHQlR2TQpFUWlDdytDTkg1UWN1WE1vQXJxMkx3MnQ4azZUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTbzNYczQwR1RhbkpPZ3V2SlJDSHNucldRU1JUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWZvc3dFaHdrVgpncHFkbW1mTzIyL2lhZElTaUJiT2RTZzltWCtJN2puVUt3QnlHWkt1RmFRaDdYeHNPbmhBcXBnU1pnalpLYUJnCndFdkxwWThORXBQVWxQVWwxUWNmcVBZVHVHbXZ6d0tncmVPZ0F3bkoyaGRmYW8wZzRzdUFLb2lYWUxPbTJsSDkKRlJsK3p3MUVYK1lmRE8rZEJyYTc0NDZaWDhUOG5jSXJqYjBrSW5WRUFudU84cXZOaXpHWkorQm5SUGMvYXBnVApRdFQ1UEhTaVhMdjVCWUN5MjIwRVNFWTVDZnRrYzRpelp3dnJaUmFtRXhNQnAzeTlPQmlvN3BqSnlUNDNpQkt5CmJZVEZZNm5zMXcvV2Vqb0FxK1Q2V3dZSnJyc2x3YmJBV0U5NGVNbDY4MXFVWnl6ZkdXQUp5Q1dqbXFlUlZRWDcKbk5UNno3aFcyd3QwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

    server: https://192.168.1.91:6443
  name: kubernetes

users:
- name: sunjay
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZCMHNEWXhTZDQzWXNFeXhsVi1CcTB0WVZ5QVhZQk91d182NW5sRU1fSTQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzgxNzg0NjQ0LCJpYXQiOjE3ODE3ODEwNDQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMDAwYTZhNmUtOTE1Yi00OWY2LWFiMjMtYWM0YmFlMTQwMDg2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InN1bmpheSIsInVpZCI6Ijk5Nzg3NjIwLWVkNmItNDQ2ZS1hZWNiLWM0ODA0YzdhMWVhNiJ9fSwibmJmIjoxNzgxNzgxMDQ0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6amVua2luczpzdW5qYXkifQ.KeFxZBk3YPnYiTZd5xAEd7Q9aqZ3Oc02uZlBhUD2dPe6hl7qtsI1NQsGspMEfMvpIhmDm9f-khsbPgdQuXrm-bGfZO3zh7X86i-wz7qIY1HEhpmZnKZ0plcFROmmASDs-muCjKb-5xni8kR1VIM5EY57zEY4yMTox8PumVnpOkYihNzb3sP9isRkuSw3laH7ChqQuRTAUhdr7Bv67Ct7l0VtaH-mUCD_iOqpDCb9ATHeAriipsWTiTwII4m59tpbd-AG9hN1gqzlnHwtbjcNB0mBWBWfZ1XXTz0JAoRSi6FwyFFwlce1fYuwvt4uRAsXm8aIHxUWRFW-a-Qep1qViw


contexts:
- context:
    cluster: kubernetes
    user: sunjay
    namespace: jenkins
  name: sunjay-context

current-context: sunjay-context


# kubectl config view --raw (to get  certificate-authority-data and add in that section) 
# kubectl create token sunjay -n jenkins (ADD THIS TOKEN IN SUNJAY-CONFIG.YAML)
# kubectl --kubeconfig=sunjay-config.yaml get pods -n jenkins
